# Generated by Django 5.1.9 on 2025-05-15 21:40

import django.db.models.deletion
import judo_profiles.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Technique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codename', models.CharField(max_length=3)),
                ('name', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('weight', models.FloatField()),
                ('primary_side', models.PositiveIntegerField(choices=[(1, 'Left'), (2, 'Right'), (3, 'Both')])),
                ('year', models.PositiveIntegerField()),
                ('changed_on', models.DateField(auto_now=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profiles_changed', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profiles_created', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': (('manage_profile', 'Manage Permissions'),),
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('side', models.BooleanField(choices=[(True, 'l'), (False, 'r')])),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='judo_profiles.profile')),
            ],
        ),
        migrations.CreateModel(
            name='OwnTechnique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('side', models.BooleanField(choices=[(True, 'l'), (False, 'r')])),
                ('state', models.PositiveIntegerField()),
                ('direction', models.PositiveIntegerField()),
                ('left_position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='left_position_owntechniques', to='judo_profiles.position')),
                ('right_position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='right_position_owntechniques', to='judo_profiles.position')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='judo_profiles.profile')),
                ('technique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='judo_profiles.technique')),
            ],
        ),
        migrations.CreateModel(
            name='CombinationRank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='judo_profiles.profile')),
                ('technique1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='technique1_combinations', to='judo_profiles.technique')),
                ('technique2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='technique2_combinations', to='judo_profiles.technique')),
            ],
        ),
        migrations.CreateModel(
            name='TechniqueRank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('type', models.PositiveIntegerField()),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='judo_profiles.profile')),
                ('technique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='judo_profiles.technique')),
            ],
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(default=judo_profiles.models.gen_token, editable=False, max_length=40, unique=True)),
                ('valid_until', models.DateField(default=judo_profiles.models.calc_date)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
