# Generated by Django 5.2.4 on 2025-07-27 05:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imprint', models.TextField(blank=True, null=True)),
                ('privacy_contact', models.TextField(blank=True, null=True)),
                ('token_expiration', models.PositiveIntegerField(default=2)),
                ('changed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Technique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codename', models.CharField(max_length=3)),
                ('name', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField()),
                ('primary_side', models.PositiveIntegerField(choices=[(1, 'Left'), (2, 'Right'), (3, 'Both')])),
                ('year', models.PositiveIntegerField()),
                ('created_at', models.DateField(auto_now_add=True)),
                ('changed_at', models.DateField(auto_now=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profiles_changed', to=settings.AUTH_USER_MODEL)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profiles_created', to=settings.AUTH_USER_MODEL)),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profiles_managed', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': (('manage_profile', 'Manage Permissions'),),
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('side', models.BooleanField(choices=[(True, 'l'), (False, 'r')])),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='judo_profiles.profile')),
            ],
        ),
        migrations.CreateModel(
            name='OwnTechnique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('side', models.BooleanField(choices=[(True, 'l'), (False, 'r')])),
                ('state', models.PositiveIntegerField()),
                ('direction', models.PositiveIntegerField()),
                ('left_position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='left_position_owntechniques', to='judo_profiles.position')),
                ('right_position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='right_position_owntechniques', to='judo_profiles.position')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='judo_profiles.profile')),
                ('technique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='judo_profiles.technique')),
            ],
        ),
        migrations.CreateModel(
            name='CombinationRank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='judo_profiles.profile')),
                ('technique1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='technique1_combinations', to='judo_profiles.technique')),
                ('technique2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='technique2_combinations', to='judo_profiles.technique')),
            ],
        ),
        migrations.CreateModel(
            name='TechniqueRank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('type', models.PositiveIntegerField()),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='judo_profiles.profile')),
                ('technique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='judo_profiles.technique')),
            ],
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash', models.CharField(editable=False, unique=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
