# Generated by Django 5.1.7 on 2025-03-16 20:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Technique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codename', models.CharField(max_length=3)),
                ('name', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('weight', models.FloatField()),
                ('primary_side', models.PositiveIntegerField(choices=[(1, 'Left'), (2, 'Right'), (3, 'Both')])),
                ('year', models.PositiveIntegerField()),
                ('updated_on', models.DateField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profiles_created', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': (('manage_profile', 'Manage Permissions'),),
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('side', models.BooleanField(choices=[(True, 'l'), (False, 'r')])),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.profile')),
            ],
        ),
        migrations.CreateModel(
            name='OwnTechnique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('side', models.BooleanField(choices=[(True, 'l'), (False, 'r')])),
                ('state', models.CharField(choices=[('W', 'wettkampfstabil'), ('T', 'Training'), ('Z', 'zu lernen')], max_length=1)),
                ('direction', models.PositiveIntegerField()),
                ('left_position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='left_position_owntechniques', to='profiles.position')),
                ('right_position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='right_position_owntechniques', to='profiles.position')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.profile')),
                ('technique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.technique')),
            ],
        ),
        migrations.CreateModel(
            name='CombinationRank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.profile')),
                ('technique1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='technique1_combinations', to='profiles.technique')),
                ('technique2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='technique2_combinations', to='profiles.technique')),
            ],
        ),
        migrations.CreateModel(
            name='TechniqueRank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('type', models.CharField(max_length=8)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.profile')),
                ('technique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.technique')),
            ],
        ),
    ]
