services:
  db:
    image: postgres:16
    volumes:
      - db-data:/var/lib/postgresql/data
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_DB=${DATABASE_NAME}
  app:
    build:
      context: .
    depends_on:
      - db
    restart: unless-stopped
    environment:
      - ALLOWED_URLS=${ALLOWED_URLS}
      - SECRET_KEY=${SECRET_KEY}
      - DATABASE_ENGINE=postgresql
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
    volumes:
      - static:/app/staticfiles
  proxy:
    image: nginx:1.27.4
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - static:/app/staticfiles
    ports:
      - 8000:80
    depends_on:
      - app

volumes:
  db-data: {}
  static: {}
