services:
  db:
    image: postgres:16
    volumes:
      - db-data:/var/lib/postgresql/data
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_DB=${DATABASE_NAME}
  app:
    build:
      context: .
    depends_on:
      - db
    restart: unless-stopped
    environment:
      - PUBLIC_URL=${PUBLIC_URL}
      - SECRET_KEY=${SECRET_KEY}
      - DATABASE_ENGINE=postgresql
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
    volumes:
      - static:/app/staticfiles
  proxy:
    build: ./nginx
    volumes:
      - static:/app/staticfiles
    ports:
      - 7000:80
    depends_on:
      - app

volumes:
  db-data: {}
  static: {}
