services:
  db:
    image: postgres:16
    volumes:
      - db-data:/var/lib/postgresql/data
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_DB=${DATABASE_NAME}
  app:
    build:
      context: .
    image: technicfan/django_judo_profiles:latest
    depends_on:
      - db
    restart: unless-stopped
    environment:
      - DEBUG=${DEBUG}
      - DATABASE_ENGINE=${DATABASE_ENGINE}
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
    ports:
      - 7000:8000

volumes:
  db-data: {}
